### ISSUE TITLE
Update the AUR Repo

### ISSUE THREAD

**Issue by Yash-Handa** [Yash-Handa/logo-ls#13]
Hi @JojiiOfficial can you update the AUR repo

Thanks

**Comment by JojiiOfficial** [comment]
Just flag it as out of date. I'll get an email and update it asap

**Comment by JojiiOfficial** [comment]
I just updated the AUR package. You can close this issue. In future please flag the package as "Out of Date" on the AUR webinterface or update it yourself if you want to make it happen instantly.
