### ISSUE TITLE
Support for sub-extensions

### ISSUE THREAD

**Issue by peteromio** [Yash-Handa/logo-ls#20]
it would be possible to support sub extensions like * .service.ts *.test.ts

**Comment by Yash-Handa** [comment]
Hey @peteromio, That's a really cool idea. I was actually working on it this feature and is now ready.
The next version of `logo-ls` will support sub-extensions.

If you want you can build the logo-ls from the source at or after https://github.com/Yash-Handa/logo-ls/commit/c6c7cf7b1f62c1ca7dd8ead79d898b5fe41b046d commit to see it in action.

List of sub-extensions added for now:

- `routing.tsx`
- `routing.js`
- `routing.jsx`
- `routes.ts`
- `routes.tsx`
- `routes.js`
- `routes.jsx`
- `sln.dotsettings`
- `d.ts`
- `vcxitems.filters`
- `vcxproj.filters`
- `js.map`
- `mjs.map`
- `css.map`
- `spec.ts`
- `e2e-spec.ts`
- `test.ts`
- `ts.snap`
- `spec.tsx`
- `test.tsx`
- `tsx.snap`
- `spec.jsx`
- `test.jsx`
- `jsx.snap`
- `spec.js`
- `e2e-spec.js`
- `test.js`
- `js.snap`
- `tf.json`
- `blade.php`
- `inky.php`
- `gitlab-ci.yml`
- `stories.js`
- `stories.jsx`
- `story.js`
- `story.jsx`
- `stories.ts`
- `stories.tsx`
- `story.ts`
- `story.tsx`
- `azure-pipelines.yml`
- `azure-pipelines.yaml`

and a special `_test.go` for .go test files

**Comment by peteromio** [comment]
Great, congratulations on all your work 😘
