### ISSUE TITLE
Error display font in terminal

### ISSUE THREAD

**Issue by dcduc168** [Yash-Handa/logo-ls#48]
![image](https://github.com/Yash-Handa/logo-ls/assets/70695937/f885e9b9-08be-43df-bcf1-f2a9dc522852)
Now im using Ubuntu 22.04 LTS, Xfce Terminal with Hack NF font but it can not display logo properly. Hope anyone can help me :( Or anyway to list file with icon. Many thanks!

**Comment by YitzhakMizrahi** [comment]
@m3r1t168 I was having the same issue. I have downloaded nerd fonts from a previous release and that fixed. The release I used is this one. https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0. Happy hacking!

**Comment by dcduc168** [comment]
@YitzhakMizrahi Thanks for your help. I solved the problem thanks to your advice. Thanks, again.
